# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HardPlant 개발블로그
email: abc7988se@naver.com
description: > # this means to ignore newlines until "baseurl:"
  QA & 자동화 방법, 개발 회고 등을 적은 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hardplant.github.io" # the base hostname & protocol for your site
twitter_username: abc79888se
github_username:  HardPlant

# Build settings
markdown: kramdown
